<?php /** @noinspection ALL */


include_once 'WordGranules.php';

/**
 * Implements hook_node_presave($node)
 * Adds a Unicode sortable Tibetan string to the Tib Sort field for any node saved (inserted or updated)
 *
 * @param $node
 */
function tibarmy_sort_node_presave($node) {
  drupal_set_message('In node presave of tibarmy sort');
  module_load_include('inc', 'tibarmy_sort', 'tibarmy_sort');
  tibarmy_sort_field_add($node);
}

